services:
  db:
    image: postgis/postgis:18-3.6
    container_name: commonground-db
    environment:
      POSTGRES_USER: neo
      POSTGRES_PASSWORD: your_password
      POSTGRES_DB: commonground
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql

volumes:
  postgres_data: